apiVersion: 1

datasources:
  - name: CloudWatch-AWS-Academy
    type: cloudwatch
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      authType: default
      defaultRegion: us-east-1